# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    # Python27:
    #   python.version: '2.7'
    # Python35:
    #   python.version: '3.5'
    # Python36:
    #   python.version: '3.6'
    Python37:
      python.version: '3.7'

variables: 
  - group: var-group

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
      pip install pytest
      pytest --junitxml=reports/basic.xml 
  displayName: 'Run tests'

- script: |
      echo "$(test)"
  condition: always()
  displayName: 'Environment Variable'

- task: PublishTestResults@2
  inputs:
    # testRunner: "VSTEST"
    # testResultsFiles: '**/TEST-*.trx'
    testResultsFiles: 'reports/basic.xml'
    testRunTitle: '$(Agent.OS) - $(Build.DefinitionName) - Python $(python.version)'
    publishRunAttachments: true
  condition: succeededOrFailed()

  
      




